---

language: python

sudo:
  - required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local | tee log
  - grep ' changed=0 ' log || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
